---
- name: update
  apt:
    update_cache=yes cache_valid_time=3600
  tags:
    - elk

- name: install elastic
  ansible.builtin.apt:
    pkg:
    - elasticsearch
    - logstash
    - kibana
  tags:
    - elk

- name: copy conf logstash
  template:
    src: logstash-nginx-es.conf
    dest: /var/lib/logstash/logstash-nginx-es.conf
  tags:
    - elk

- name: restart logstash
  service:
    name: logstash.service
    state: restarted
  tags:
    - elk

- name: Add option jvm
  lineinfile:
    path: "/etc/elasticsearch/jvm.options"
    line: '-Xmx1g'
  tags:
    - elk

- name: Add option jvm
  lineinfile:
    path: "/etc/elasticsearch/jvm.options"
    line: '-Xms1g'
  tags:
    - elk

- name: enable log
  replace:
    path: "/etc/elasticsearch/elasticsearch.yml"
    regexp: 'enabled: true'
    replace: 'enabled: false'
  tags:
    - elk

- name: enable log
  replace:
    path: "/etc/elasticsearch/elasticsearch.yml"
    regexp: 'xpack.security.enrollment.enabled: false'
    replace: 'xpack.security.enrollment.enabled: true'
  tags:
    - elk

- name: restart es
  service:
    name: elasticsearch.service
    state: restarted
  tags:
    - elk

- name: enable kibana
  replace:
    path: "/etc/kibana/kibana.yml"
    regexp: '#server.host: "localhost"'
    replace: 'server.host: "0.0.0.0"'
  tags:
    - elk

- name: enable kibana
  replace:
    path: "/etc/kibana/kibana.yml"
    regexp: '#server.port: "5601"'
    replace: 'server.port: "5601"'
  tags:
    - elk

- name: restart kibana
  service:
    name: kibana.service
    state: restarted
  tags:
    - elk

